# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12CcB1C7WQIa5w19d3T1JSswajf2EMxeB
"""

import gymnasium as gym

env = gym.make("LunarLander-v3", render_mode="human")
observation, info = env.reset()
print("Initial Observation:", observation)
run = True
total_reward = 0
def cmd(obs):
    global y
    global yv
    global theta
    global av
    x = obs[0]
    y = obs[1]
    xv = obs[2]
    yv = obs[3]
    theta = obs[4]
    av = obs[5]


    if x>.07 :
        return 1
    if x<-.07:
        return 3
    if theta>.01 :
        return 1

    if theta<-.01 :
        return 3


    else :
      return 0


while(run):
    action = cmd(observation)
    if y<.8 and yv>-.3:
      action = 2
      action =  2
      if av>0.5:
        action =  3
      if av<-0.5:
        action =  1
      if theta>.1 :
        action =  1

      if theta<-.1 :
        action =  3
      action = 2
    observation, reward, terminated, truncated, info = env.step(action)
    total_reward += reward

    if terminated or truncated:
        print("fo: ", observation)
        observation, info = env.reset()
        run = False

print("Total Reward:", total_reward)
env.close()

